// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(SWDGradingDbContext))]
    [Migration("20260416053523_AddPacketSimilarityReviewFlow")]
    partial class AddPacketSimilarityReviewFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entity.DocFile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamStudentId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamZipId")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsEmbedded")
                        .HasColumnType("boolean");

                    b.Property<string>("ParseMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ParsedText")
                        .HasColumnType("text");

                    b.Property<int?>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("QuestionNumber");

                    b.HasKey("Id");

                    b.HasIndex("ExamStudentId");

                    b.HasIndex("ExamZipId");

                    b.ToTable("doc_file", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Exam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ExamPaper")
                        .HasColumnType("text");

                    b.Property<string>("OriginalExcel")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamCode")
                        .IsUnique();

                    b.ToTable("exam", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ExamQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionText")
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedDocSection")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("exam_question", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ExamStudent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("exam_student", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ExamZip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExtractedPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ParseStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ParseSummary")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ZipName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ZipPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("exam_zip", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Flag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("MatchedQuestionPacketId")
                        .HasColumnType("bigint");

                    b.Property<long>("QuestionPacketId")
                        .HasColumnType("bigint");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("TeacherDecision")
                        .HasColumnType("boolean");

                    b.Property<string>("TeacherNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ThresholdUsed")
                        .HasColumnType("DECIMAL(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("MatchedQuestionPacketId");

                    b.HasIndex("ReviewedByUserId");

                    b.HasIndex("QuestionPacketId", "MatchedQuestionPacketId", "Source")
                        .IsUnique();

                    b.ToTable("flag", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Grade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("ExamStudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("GradedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GradedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalScore")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExamStudentId");

                    b.ToTable("grade", (string)null);
                });

            modelBuilder.Entity("Model.Entity.GradeDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoDetectResult")
                        .HasColumnType("TEXT");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<long>("GradeId")
                        .HasColumnType("bigint");

                    b.Property<long>("RubricId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Score")
                        .HasColumnType("DECIMAL(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("GradeId");

                    b.HasIndex("RubricId");

                    b.ToTable("grade_detail", (string)null);
                });

            modelBuilder.Entity("Model.Entity.GradeExport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.HasIndex("UserId");

                    b.ToTable("GradeExport", (string)null);
                });

            modelBuilder.Entity("Model.Entity.ProcessingJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionId", "JobType", "CreatedAt");

                    b.ToTable("processing_job", (string)null);
                });

            modelBuilder.Entity("Model.Entity.QuestionPacket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ExamQuestionId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamStudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("ExtractedAnswerText")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrlsJson")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ParseConfidence")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<string>("ParseNotes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<long>("SubmissionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("ExamStudentId");

                    b.HasIndex("SubmissionId", "QuestionNumber")
                        .IsUnique();

                    b.HasIndex("ExamId", "ExamStudentId", "QuestionNumber");

                    b.ToTable("question_packet", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Rubric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AutoCheckRule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Criterion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("ExamQuestionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("DECIMAL(5,2)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExamQuestionId");

                    b.ToTable("rubric", (string)null);
                });

            modelBuilder.Entity("Model.Entity.SimilarityCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CheckedByUserId")
                        .HasColumnType("integer");

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("DECIMAL(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CheckedByUserId");

                    b.HasIndex("ExamId");

                    b.ToTable("similarity_check", (string)null);
                });

            modelBuilder.Entity("Model.Entity.SimilarityResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AIVerificationResult")
                        .HasColumnType("text");

                    b.Property<DateTime?>("AIVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DocFile1Id")
                        .HasColumnType("bigint");

                    b.Property<long>("DocFile2Id")
                        .HasColumnType("bigint");

                    b.Property<long>("SimilarityCheckId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SimilarityScore")
                        .HasColumnType("DECIMAL(5,4)");

                    b.Property<string>("Student1Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Student2Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TeacherNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("TeacherVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("TeacherVerifiedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("VerificationStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DocFile1Id");

                    b.HasIndex("DocFile2Id");

                    b.HasIndex("SimilarityCheckId");

                    b.HasIndex("TeacherVerifiedByUserId");

                    b.ToTable("similarity_result", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Student", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClassName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("student", (string)null);
                });

            modelBuilder.Entity("Model.Entity.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("ExamId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExamStudentId")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("OriginalFileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SourceFormat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExamStudentId");

                    b.HasIndex("ExamId", "ExamStudentId", "Attempt")
                        .IsUnique();

                    b.ToTable("submission", (string)null);
                });

            modelBuilder.Entity("Model.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("TeacherCode")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Model.Entity.DocFile", b =>
                {
                    b.HasOne("Model.Entity.ExamStudent", "ExamStudent")
                        .WithMany()
                        .HasForeignKey("ExamStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.ExamZip", "ExamZip")
                        .WithMany()
                        .HasForeignKey("ExamZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExamStudent");

                    b.Navigation("ExamZip");
                });

            modelBuilder.Entity("Model.Entity.ExamQuestion", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Model.Entity.ExamStudent", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany("ExamStudents")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.User", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.Entity.ExamZip", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Model.Entity.Flag", b =>
                {
                    b.HasOne("Model.Entity.QuestionPacket", "MatchedQuestionPacket")
                        .WithMany("MatchedFlags")
                        .HasForeignKey("MatchedQuestionPacketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.QuestionPacket", "QuestionPacket")
                        .WithMany("SourceFlags")
                        .HasForeignKey("QuestionPacketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.User", "ReviewedByUser")
                        .WithMany("ReviewedFlags")
                        .HasForeignKey("ReviewedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MatchedQuestionPacket");

                    b.Navigation("QuestionPacket");

                    b.Navigation("ReviewedByUser");
                });

            modelBuilder.Entity("Model.Entity.Grade", b =>
                {
                    b.HasOne("Model.Entity.ExamStudent", "ExamStudent")
                        .WithMany("Grades")
                        .HasForeignKey("ExamStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamStudent");
                });

            modelBuilder.Entity("Model.Entity.GradeDetail", b =>
                {
                    b.HasOne("Model.Entity.Grade", "Grade")
                        .WithMany("Details")
                        .HasForeignKey("GradeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Rubric", "Rubric")
                        .WithMany()
                        .HasForeignKey("RubricId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Grade");

                    b.Navigation("Rubric");
                });

            modelBuilder.Entity("Model.Entity.GradeExport", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany("GradeExports")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.User", "Teacher")
                        .WithMany("GradeExports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Model.Entity.ProcessingJob", b =>
                {
                    b.HasOne("Model.Entity.Submission", "Submission")
                        .WithMany("ProcessingJobs")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Model.Entity.QuestionPacket", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany("QuestionPackets")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.ExamQuestion", "ExamQuestion")
                        .WithMany("QuestionPackets")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Model.Entity.ExamStudent", "ExamStudent")
                        .WithMany("QuestionPackets")
                        .HasForeignKey("ExamStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.Submission", "Submission")
                        .WithMany("QuestionPackets")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamQuestion");

                    b.Navigation("ExamStudent");

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Model.Entity.Rubric", b =>
                {
                    b.HasOne("Model.Entity.ExamQuestion", "ExamQuestion")
                        .WithMany("Rubrics")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("Model.Entity.SimilarityCheck", b =>
                {
                    b.HasOne("Model.Entity.User", "CheckedByUser")
                        .WithMany()
                        .HasForeignKey("CheckedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CheckedByUser");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Model.Entity.SimilarityResult", b =>
                {
                    b.HasOne("Model.Entity.DocFile", "DocFile1")
                        .WithMany()
                        .HasForeignKey("DocFile1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.DocFile", "DocFile2")
                        .WithMany()
                        .HasForeignKey("DocFile2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Model.Entity.SimilarityCheck", "SimilarityCheck")
                        .WithMany("SimilarityResults")
                        .HasForeignKey("SimilarityCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.User", "TeacherVerifiedByUser")
                        .WithMany()
                        .HasForeignKey("TeacherVerifiedByUserId");

                    b.Navigation("DocFile1");

                    b.Navigation("DocFile2");

                    b.Navigation("SimilarityCheck");

                    b.Navigation("TeacherVerifiedByUser");
                });

            modelBuilder.Entity("Model.Entity.Submission", b =>
                {
                    b.HasOne("Model.Entity.Exam", "Exam")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Entity.ExamStudent", "ExamStudent")
                        .WithMany("Submissions")
                        .HasForeignKey("ExamStudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("ExamStudent");
                });

            modelBuilder.Entity("Model.Entity.Exam", b =>
                {
                    b.Navigation("ExamStudents");

                    b.Navigation("GradeExports");

                    b.Navigation("QuestionPackets");

                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Model.Entity.ExamQuestion", b =>
                {
                    b.Navigation("QuestionPackets");

                    b.Navigation("Rubrics");
                });

            modelBuilder.Entity("Model.Entity.ExamStudent", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("QuestionPackets");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Model.Entity.Grade", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Model.Entity.QuestionPacket", b =>
                {
                    b.Navigation("MatchedFlags");

                    b.Navigation("SourceFlags");
                });

            modelBuilder.Entity("Model.Entity.SimilarityCheck", b =>
                {
                    b.Navigation("SimilarityResults");
                });

            modelBuilder.Entity("Model.Entity.Submission", b =>
                {
                    b.Navigation("ProcessingJobs");

                    b.Navigation("QuestionPackets");
                });

            modelBuilder.Entity("Model.Entity.User", b =>
                {
                    b.Navigation("GradeExports");

                    b.Navigation("ReviewedFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
